- alias: USDC/USD
  id: "0xeaa020c61cc479712813461ce153894a96a6c00b21ed0cfc2798d1f9a9e9c94a"
  time_difference: 60
  price_deviation: 0.5
  confidence_ratio: 1
  early_update:
    time_difference: 30
    price_deviation: 0.5
    confidence_ratio: 0.1
- alias: ETH/USD
  id: "0xff61491a931112ddf1bd8147cd1b641375f79f5825126d665480874634fd0ace"
  time_difference: 60
  price_deviation: 0.5
  confidence_ratio: 1
  early_update:
    time_difference: 30
    price_deviation: 0.5
    confidence_ratio: 0.1